services:
  gui:
    image: ${MM_IMAGE}
    volumes:
      # removes error messages, not needed for running:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      # xserver:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/node/.Xauthority
      # labwc
      - $LAB_WC_SOCK_DIR:$LAB_WC_SOCK_DIR
    privileged: true
    environment:
      # xserver:
      - DISPLAY=unix:0.0
      # labwc
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=${LAB_WC_SOCK_DIR}
      # GPU
      - ELECTRON_ENABLE_GPU
    shm_size: "256mb"
  # server
  server:
    image: ${MM_IMAGE}
    volumes:
      - ${VOLUME_CONFIG}
      - ${VOLUME_MODULES}
      - ${VOLUME_CSS}
    environment:
      - MM_OVERRIDE_DEFAULT_MODULES
      - MM_SHOW_CURSOR
      - MM_SCENARIO
      - MM_MODULES_DIR
      - MM_CUSTOMCSS_FILE
    ports:
      - ${MM_SERVER_PORTS}
  # electron
  electron:
    volumes:
      - ${VOLUME_CONFIG}
      - ${VOLUME_MODULES}
      - ${VOLUME_CSS}
    environment:
      - MM_OVERRIDE_DEFAULT_MODULES
      - MM_SHOW_CURSOR
      - MM_SCENARIO
      - MM_MODULES_DIR
      - MM_CUSTOMCSS_FILE
    extends:
      service: gui
    network_mode: host
  # client
  client:
    extends:
      service: gui
    command: "node clientonly --address ${MM_CLIENT_ADDRESS} --port ${MM_CLIENT_PORT}"
