services:
  base:
    image: ${MM_IMAGE}
    volumes:
      - ${VOLUME_CONFIG}
      - ${VOLUME_MODULES}
      - ${VOLUME_CSS}
  base_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: base
  server_no:
    environment:
      - MM_OVERRIDE_DEFAULT_MODULES
      - MM_OVERRIDE_CSS
      - MM_SHOW_CURSOR
      - MM_SCENARIO
      - MM_MODULES_DIR
      - MM_CUSTOMCSS_FILE
    ports:
      - ${MM_SERVER_PORTS}
    extends:
      service: base
  server_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: server_no
  electron_no:
    extends:
      service: base
    volumes:
      # removes error messages, not needed for running:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      # xserver:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/node/.Xauthority
      # labwc
      - $LAB_WC_SOCK_DIR:$LAB_WC_SOCK_DIR
    privileged: true
    devices:
      - /dev/vchiq
    environment:
      - MM_OVERRIDE_DEFAULT_MODULES
      - MM_OVERRIDE_CSS
      - MM_SHOW_CURSOR
      - MM_SCENARIO
      - MM_MODULES_DIR
      - MM_CUSTOMCSS_FILE
      # xserver:
      - DISPLAY=unix:0.0
      # labwc
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=${LAB_WC_SOCK_DIR}
    network_mode: host
    shm_size: "128mb"
  electron_init:
    depends_on:
      init:
        condition: service_completed_successfully
    extends:
      service: electron_no
  client_no:
    image: ${MM_IMAGE}
    volumes:
      # removes error messages, not needed for running:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      # xserver:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/node/.Xauthority
      # labwc
      - $LAB_WC_SOCK_DIR:$LAB_WC_SOCK_DIR
    privileged: true
    environment:
      # xserver:
      - DISPLAY=unix:0.0
      # labwc
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=${LAB_WC_SOCK_DIR}
    shm_size: "128mb"
    command: "node clientonly --address ${MM_CLIENT_ADDRESS} --port ${MM_CLIENT_PORT}"
