services:
  init:
    container_name: init
    user: root
    environment:
      - MM_UID
      - MM_GID
      - MM_CHMOD
    image: ${MM_IMAGE}
    volumes:
      - ../..:/magicmirror
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "change permissions for mounted folders ..."
        cd /magicmirror
        chown -R ${MM_UID}:${MM_GID} mounts
        chmod -R ${MM_CHMOD} mounts
        git config --global --add safe.directory /magicmirror
        git update-index --assume-unchanged mounts/css/custom.css
        echo "done."
