services:
  xserver:
    container_name: xserver
    image: ${XSERVER_IMAGE}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0.0
      - XRANDR_PARAMS
      - XRANDR_DELAY
    restart: unless-stopped
