#!/bin/bash

for _var in $(cat ../.gitlab-ci.yml | gojq --yaml-input -r '.variables' | sed 's|{||g;s|}||g;s|\s*"\s*||g;s|\s*:\s*|=|g;s|,||g'); do
  if [[ "$_var" =~ .*_VERSION.* ]]; then
    _key="$(echo $_var | sed -r 's|(.*)=.*|\1|g')"
    _value="$(echo $_var | sed -r 's|.*=(.*)|\1|g')"
    sed 's|{{ '$_key' }}|'$_value'|g' -i ./docs/images.md
  fi
done


