services:
  init:
    container_name: init
    user: root
    environment:
      STARTENV: init
    extends:
      file: includes/fedora.yaml
      service: fedora
  xserver:
    container_name: xserver
    image: ${XSERVER_IMAGE}
    volumes:
      - /run/udev/data:/run/udev/data:z
    restart: unless-stopped
    extends:
      file: includes/fedora.yaml
      service: fedora
  magicmirror:
    container_name: mm
    extends:
      file: includes/fedora.yaml
      service: fedora
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:z
    depends_on:
      init:
        condition: service_completed_successfully
      xserver:
        condition: service_started
    privileged: true # avoids dbus errors in logs
    devices:
      - /dev/gpiochip0
      - /dev/gpiochip1
    shm_size: "128mb"
    restart: unless-stopped
